### ISSUE TITLE
[feature request] Add noise cancel control

### ISSUE THREAD

**Issue by reorx** [godbout/alfred-airpodspro-connector#13]
Thank you for creating this helpful tool. I wonder if it's possible to add noise control to this workflow, like typing`apc adaptive` to switch to the adaptive mode.

**Comment by godbout** [comment]
this Workflow is using [blueutil](https://github.com/toy/blueutil) behind the scenes to connect/disconnect bluetooth devices. blueutil doesn't have anything related to audio devices in particular, and really is about connecting. [alfred-airpodspro-battery](https://github.com/godbout/alfred-airpodspro-battery) would be a better target but then it'd be about controller your AirPods rather than reading data, so it's kind of another Workflow/work altogether. not seeing myself doing this.

**Comment by reorx** [comment]
Got it, thanks for the reply

Sincerely,
Xiao Meng

**Comment by godbout** [comment]
不客气。maybe try to post on the battery Workflow and i'll think about it more 哈哈哈哈哈哈哈

**Comment by reorx** [comment]
That's a great idea, I have added the new issue.

Besides, I read your website and projects, they are really inspiring (the about page), and thoughtful (sleeplessmind.info), it's really nice to get to know you.

**Comment by godbout** [comment]
> Besides, I read your website and projects, they are really inspiring (the about page), and thoughtful (sleeplessmind.info), it's really nice to get to know you.

🙏️🙏️🙏️ sleeplessmind.info is super focused on writings. https://glmb.today is where you get most of the day to day (month to month...) updates tho 😅️ 谢谢你！也非常好认识你。你在中国哪儿？

**Comment by godbout** [comment]
seeing that sleeplessmind.info needs some update in the about part. nice. will do.
